[workspace]
resolver = "2"
members = ["crates/raven-agent", "crates/raven-server", "crates/raven-proto"]

[workspace.package]
version = "0.1.0"
edition = "2024"
license = "MIT"
repository = "https://github.com/bakayu/raven"

[workspace.dependencies]
# runtime
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
futures = "0.3"

# gRPC / Protobuf
tonic = { version = "0.14", features = [
    "transport",
    "tls-ring",
    "tls-webpki-roots",
] }
prost = "0.14"
prost-types = "0.14"
tonic-prost = "0.14"
tonic-prost-build = "0.14"

# HTTP
axum = { version = "0.8", features = ["ws", "macros"] }
axum-extra = { version = "0.12", features = ["cookie", "typed-header"] }
tower = "0.5"
reqwest = { version = "0.13", features = ["json"] }
tower-http = { version = "0.6", features = ["fs", "cors", "trace"] }
hyper = "1"

# Serialization
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "1"

# Database
sqlx = { version = "0.8", features = [
    "runtime-tokio-rustls",
    "sqlite",
    "migrate",
    "macros",
    "chrono",
] }

# Auth
jsonwebtoken = { version = "10", features = ["rust_crypto"] }
argon2 = { version = "0.5", features = ["std"] }

# Notifications
lettre = { version = "0.11", default-features = false, features = [
    "tokio1-rustls-tls",
] }

# Observability
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "json"] }
tracing-bunyan-formatter = "0.3"
tracing-log = "0.2"
secrecy = { version = "0.10", features = ["serde"] }

# CLI
clap = { version = "4", features = ["derive"] }

# Agent-specific
procfs = "0.18"
rustix = { version = "1.0", features = ["fs", "process"] }
inotify = { version = "0.11", features = ["stream"] }
glob = "0.3"
hostname = "0.4"

# Misc
chrono = { version = "0.4", features = ["serde"] }
uuid = { version = "1", features = ["v4"] }
sha2 = "0.11"
hex = "0.4"
dashmap = "6"
rand = { version = "0.10", features = ["std"] }
rand_core = "0.10"
rand_distr = "0.6"
thiserror = "2"
anyhow = "1"
config = "0.15"
cookie = { version = "0.18", features = ["secure", "percent-encode"] }
time = "0.3"
